version: "3"
services:
  backend:
    build: .
    environment:
      DB_USER: zakat
      DB_PASSWORD: zakat_pwd
      DB_NAME: reviewers_db
      DB_HOST: db
      GIN_MODE: release
    ports:
      - 8080:8080
    depends_on:
      - migrate

  db:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: zakat
      POSTGRES_PASSWORD: zakat_pwd
      POSTGRES_DB: reviewers_db
    ports: []
    volumes:
      - db-data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U zakat -d reviewers_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  migrate:
    image: migrate/migrate
    command: [ "-path", "/migrations", "-database", "postgres://zakat:zakat_pwd@db:5432/reviewers_db?sslmode=disable", "up" ]
    volumes:
      - ./migrations:/migrations
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data:
